<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
  </head>
  <body>
    <button id="btn">按钮</button>
  </body>
  <script>
    /*Promise代表一个异步操作，，拥有三种状态:pending(进行中),
    fulfilled(已成功)和rejected(已失败),并且状态发生改变后，就不会在编，任何时候都可以得到这个结果.一共有两种可能
    pending->fulfilled 和 pending->rejected
    并且如果改变已经发生，在对Promise对象添加回调函数，也会立即得到这个结果，不像时间(Event)，如果错过它，再去监听，得不到结果。

    有了Promise对象，就可以将异步操作以同步操作的流程表达出来，避免了层层嵌套的回调函数。此外，Promise对象提供统一的接口，使得控制异步操作更加容易。

    Promise也有缺点，首先无法取消Promise，一旦新建它就无法取消。其次，如果不设置回调函数，Promise内部抛出的错误，不会反映到外部，并且处于pending状态时，无法得知目前进展到哪一个阶段(刚刚开始还是即将完成)

    为了行文方便，本章后面的resolved统一只指fulfilled(完成)状态，不包含rejected状态。

    Promise对象是一个构造函数,可以包含两个参数，两个参数都是函数，一个是resolved对应的函数，另一个是rejected对应的函数

    Promise对象创建之后可以为该对象创建then方法，then方法可以接受两个回调函数作为参数。第一个回调函数是Promise对象的状态变为resolved时调用，第二个回调函数是Promise对象的状态变为rejected时调用。其中，第二个函数是可选的，不一定要提供。这两个函数都接受Promise对象传出的值作为参数。

    finally方法用于指定不管 Promise 对象最后状态如何，都会执行的操作。该方法是 ES2018 引入标准的。
    promise
    .then(result => {···})
    .catch(error => {···})
    .finally(() => {···});

    */
    //Promise对象是一个构造函数
    // const promise = new Promise(function(resolve, reject) {
    //   if (5 > 3) {
    //     resolve('OK');
    //   }
    // });
    // promise.then(function(value) {
    //   console.log('status: ' + value);
    // });
    // function timeout(ms) {
    //   return new Promise((resolve, reject) => {
    //     setTimeout(reject, ms, 'done');
    //     //reject所以会执行then里面的第二个函数，输出 异常done
    //     //then可以接受两个回调函数作为参数，第一个回调函数是resolved时调用的，第二个是rejected调用的
    //   });
    // }
    // timeout(100).then(
    //   value1 => {
    //     console.log(value1);
    //   },
    //   function(value1, value2) {
    //     console.log('异常' + value1);
    //   }
    // );

    // let promise = new Promise((resolve, reject) => {
    //   console.log('begin');
    //   resolve();
    // });
    // //第一个函数是resolved调用的函数，第二个是rejected执行的函数
    // promise.then(
    //   () => {
    //     console.log('execute has been resolved');
    //   },
    //   () => {
    //     console.log('execute has been rejected');
    //   }
    // );
    // console.log('running status:');
    /*
    上面代码中，Promise 新建后立即执行，所以首先输出的是begin。然后，then方法指定的回调函数，将在当前脚本所有同步任务执行完才会执行，所以execute has been resolved最后输出。
    */

    // let p1 = new Promise((resolve, reject) => {
    //   setTimeout(() => reject(new TypeError('type has error')), 3000);
    // });

    // let p2 = new Promise((resolve, reject) => {
    //   setTimeout(() => {
    //     resolve(p1); //运行p1的状态
    //   }, 1000); //1s后执行相应的代码
    // });

    // p2.then(
    //   () => {
    //     console.log('进入了resolved作用域');
    //   },
    //   () => {
    //     console.log('进入了reject作用域');
    //   }
    // );
    //执行会输出进入了reject作用域

    // p2.then(() => {
    //   console.log('进入了resolved作用域');
    // }).catch(error => console.log(error));
    //执行会输出  TypeError: type has error

    new Promise((resolve, reject) => {
      reject(1);
      console.log('2');
      //这里会输出
      /*
        2
        console.log('进入reject');
        上面代码中，调用reject(1)以后，后面的console.log(2)还是会执行，并且会首先打印出来。这是因为立即 rejected 的 Promise 是在本轮事件循环的末尾执行，总是晚于本轮循环的同步任务。
        1

        一般来说，调用resolve或reject以后，Promise 的使命就完成了，后继操作应该放到then方法里面，而不应该直接写在resolve或reject的后面。所以，最好在它们前面加上return语句，这样就不会有意外。
        所以上面的代码 应该写成 
        return reject(1);
        // 后面的语句不会执行
        console.log(2);
      */
    }).then(
      res => {
        console.log('进入resolve');
        console.log(res);
      },
      rej => {
        console.log('进入reject');
        console.log(rej);
      }
    );
  </script>
</html>
